version: '3.9'

services:
  database:
    image: postgres:14-alpine
    container_name: db_form_anamnese
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=anamnese
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    container_name: app_form_anamnese
    ports:
      - 5000:5000
    volumes:
      - .:/usr/app
    links:
      - database
    depends_on:
      - database
volumes:
  pgdata:
    driver: local
