version: '3.9'

networks:
  db_anamnese:
    driver: bridge
services:
  database:
    image: postgres:14-alpine
    container_name: db_form_anamnese
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=anamnese
    volumes:
      - pgdata:/data/postgres
    networks:
      - db_anamnese
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app_form_anamnese
    restart: always
    environment:
      DATABASE_URL: ${DATABASE_URL}
      PORT_SERVER:  ${PORT_SERVER}
    ports:
      - 5000:5000
    volumes:
      - .:/usr/app
    links:
      - database
    networks:
      - db_anamnese
    depends_on:
      - database
volumes:
  pgdata:
    driver: local

